name: shopst
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_spinkit: ^4.1.2+1
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  email_validator: ^1.0.4
  shared_preferences: ^0.5.6+3
  google_sign_in: ^4.4.2
  auto_animated_icon: ^1.1.4
  flutter_inner_drawer: "^0.5.7+1"
  provider: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
   - family: VeganStyle
     fonts:
       - asset: assets/fonts/VeganStyle.ttf
   - family: WorkSansSemiBold
     fonts:
       - asset: assets/fonts/WorkSans-SemiBold.ttf